#pragma once
// Interface between the recompiled game code (recomp/gen_*.cpp, generated by scripts/recomp.py) and the
// host layer (host/*) that replaces DOS, DOS/4GW, the VGA/VESA hardware, the HMI SOS sound library and
// the parts of the Watcom C runtime listed in data/recomp_hle.txt.
#include "codec/lifted.h"

namespace blub {

// every recompiled function: void F_<addr>(Cpu &, Arena &, uint32_t entry)
// entry == 0: start at the function entry, otherwise at that (secondary) address
using GuestFn = void (*)(Cpu &, Arena &, uint32_t);

// generated (recomp/table.cpp)
bool dispatch_address(Cpu &c, Arena &m, uint32_t addr);   // run the code at addr; false: unknown address
const char *function_name(uint32_t addr);

// host layer
void host_call(Cpu &c, Arena &m, uint32_t addr);          // HLE function (return address is on the stack)
void host_int(Cpu &c, Arena &m, int vector);              // software interrupt
uint32_t host_in(Cpu &c, uint16_t port, int size);
void host_out(Cpu &c, uint16_t port, uint32_t value, int size);
void host_poll(Cpu &c, Arena &m);                         // timer events, input, presenting the screen
void host_hook(Cpu &c, Arena &m, uint32_t addr);          // entry of a function in data/recomp_hooks.txt
bool host_branch(Cpu &c, Arena &m, uint32_t addr);        // "0x<addr> <name> -> 0x<target>": jump there?

// indirect call: the return address is already pushed
inline void call_address(Cpu &c, Arena &m, uint32_t addr) {
    if (!dispatch_address(c, m, addr)) c.bad_target(addr);
}
// indirect jump out of the current function: the callee returns to our caller
inline void jump_address(Cpu &c, Arena &m, uint32_t addr) {
    if (!dispatch_address(c, m, addr)) c.bad_target(addr);
}

constexpr int32_t POLL_INTERVAL = 20000;   // backward branches between two host polls

}  // namespace blub

#define BLUB_POLL()                                   \
    do {                                              \
        if (--c.budget <= 0) ::blub::host_poll(c, m); \
    } while (0)
