// blub: runs Down in the Dumps (1996) from the user's original discs.
// The game logic is DID.EXE statically recompiled to C++ (src/engine/recomp, generated by
// scripts/recomp.py); src/engine/host replaces DOS, DOS/4GW, VESA, mouse, MSCDEX and the SOS sound
// library.
//
// Without arguments blub opens the launcher (settings window, src/launcher.cpp); after the game it
// returns there. With arguments the game starts directly; blub.ini provides the defaults.
#include <SDL.h>

#include <algorithm>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <stdexcept>
#include <string>

#include "host/machine.h"
#include "data/gamefs.h"
#include "host/settings.h"
#include "launcher.h"
#include "util/i18n.h"

#ifdef _WIN32
#include <windows.h>
#endif

namespace fs = std::filesystem;

static void usage() {
    std::puts(
        "usage: blub [options] [-- DID.EXE arguments]\n"
        "  (no options: settings window)\n"
        "  --launcher      open the settings window\n"
        "  --lang de|en    language of the settings window and messages (default: system language)\n"
        "  --game PATH     folder with the ISO images or the disc contents, or one .iso file\n"
        "  --save DIR      directory for DID.CFG and save games\n"
        "  --setup         run the setup program (sound/config) instead of the game\n"
        "  --fullscreen    start in fullscreen (toggle with F11 or Alt+Enter)\n"
        "  --window        start in a window\n"
        "  --scale N       window size: N x 640x480\n"
        "  --smooth        linear filtering when scaling\n"
        "  --xbrz          xBRZ upscaling (high quality)\n"
        "  --sharp         sharp pixels like the original (neither of the two)\n"
        "  --nosound       no sound\n"
        "  --volume N      master volume in percent\n"
        "  --singlepage    draw on the visible page like the original default\n"
        "  --trace         log DOS, DPMI and sound calls\n"
        "  --shots DIR     save the screen every --shot-interval seconds (testing)\n"
        "  --shot-presented  screenshots of the window contents: upscaled, with overlay (testing)\n"
        "  --quit-after S  quit after S seconds (testing)\n"
        "  --script FILE   scripted mouse/keyboard input (testing)\n"
        "  --wav FILE      record the sound (testing)\n"
        "Settings of the launcher: blub.ini in the user data directory.");
}

// Windows GUI program: write to the console we were started from, otherwise to blub.log
static void setup_output() {
#ifdef _WIN32
    if (AttachConsole(ATTACH_PARENT_PROCESS)) {
        std::freopen("CONOUT$", "w", stdout);
        std::freopen("CONOUT$", "w", stderr);
        return;
    }
    char *pref = SDL_GetPrefPath("blub", "Down in the Dumps");
    if (pref) {
        std::string log = std::string(pref) + "blub.log";
        SDL_free(pref);
        std::freopen(log.c_str(), "w", stdout);
        std::setvbuf(stdout, nullptr, _IONBF, 0);
        std::freopen(log.c_str(), "a", stderr);
    }
#endif
}

static void load_script(blub::Machine &machine, const std::string &path) {
    // "<seconds> click|rclick|move|press|release x y" / "<seconds> key <bios key hex>" /
    // "<seconds> shot|hotspots|quit"
    std::FILE *f = std::fopen(path.c_str(), "r");
    if (!f) return;
    char line[256];
    while (std::fgets(line, sizeof line, f)) {
        double t;
        char what[32] = {}, x[32] = {}, y[32] = {};
        if (line[0] == '#' || std::sscanf(line, "%lf %31s %31s %31s", &t, what, x, y) < 2) continue;
        blub::Machine::ScriptEvent e{t, what};
        e.a = int(std::strtol(x, nullptr, std::strcmp(what, "key") == 0 ? 16 : 10));
        e.b = std::atoi(y);
        machine.script.push_back(e);
    }
    std::fclose(f);
}

// run the game; returns an error message for the launcher (empty: normal end)
static std::string play(blub::HostConfig cfg, const std::string &game, bool setup) {
    cfg.game = game;
    while (cfg.save_dir.size() > 1 && (cfg.save_dir.back() == '/' || cfg.save_dir.back() == '\\')) cfg.save_dir.pop_back();
    std::error_code ec;
    fs::create_directories(fs::u8path(cfg.save_dir), ec);
    if (cfg.args.empty()) cfg.args.push_back(setup ? "SETUP\\SETUP.EXP" : "ITOON\\ITOON.EXP");
    try {
        blub::Machine machine(cfg);
        if (!cfg.script.empty()) load_script(machine, cfg.script);
        std::string err;
        if (!machine.init(&err)) return blub::tr("Start fehlgeschlagen: ", "Could not start: ") + err;
        std::printf("save directory: %s\n", cfg.save_dir.c_str());
        const int code = machine.run();
        if (code >= 3) return blub::tr("Das Spiel wurde wegen eines Fehlers beendet (Code ", "The game stopped because of an error (code ") +
                              std::to_string(code) + blub::tr("), siehe blub.log.", "), see blub.log.");
    } catch (const std::exception &e) {
        return std::string(blub::tr("Fehler: ", "Error: ")) + e.what();
    }
    return "";
}

static blub::HostConfig host_config(const blub::Settings &s) {
    blub::HostConfig c;
    c.save_dir = s.effective_save_dir();
    c.fullscreen = s.fullscreen;
    c.scale = s.scale;
    c.smooth = s.smooth;
    c.xbrz = s.xbrz;
    c.vsync = s.vsync;
    c.dualpage = s.dualpage;
    c.nosound = !s.sound;
    c.volume = s.volume;
    c.esc_skips = s.esc_skips;
    return c;
}

int main(int argc, char **argv) {
    setup_output();
    const std::string ini = blub::Settings::default_path();
    blub::Settings settings;
    const bool have_ini = settings.load(ini);
    settings.apply_language();
    if (settings.game_dir.empty()) {
        if (const char *env = std::getenv("BLUB_GAME")) settings.game_dir = env;
    }
    // portable installation: ISOs (or the disc contents) in a subfolder next to the program
    if (settings.game_dir.empty() || !blub::check_game_dir(settings.game_dir).exe) {
        const std::string found = blub::find_portable_game_data(blub::Settings::program_dir());
        if (!found.empty()) settings.game_dir = found;
    }

    bool launcher = argc == 1 && (settings.show_launcher || !have_ini || !blub::check_game_dir(settings.game_dir).exe);
    blub::HostConfig cfg = host_config(settings);
    std::string game = settings.game_dir;
    bool setup = false;
    for (int i = 1; i < argc; i++) {
        std::string a = argv[i];
        auto next = [&]() -> std::string { return i + 1 < argc ? argv[++i] : ""; };
        if (a == "--launcher") launcher = true;
        else if (a == "--lang") {
            settings.language = next();
            settings.apply_language();
        }
        else if (a == "--game") game = next();
        else if (a == "--save") cfg.save_dir = next();
        else if (a == "--setup") setup = true;
        else if (a == "--fullscreen") cfg.fullscreen = true;
        else if (a == "--window") cfg.fullscreen = false;
        else if (a == "--scale") cfg.scale = std::max(1, std::atoi(next().c_str()));
        else if (a == "--smooth") cfg.smooth = true;
        else if (a == "--xbrz") cfg.xbrz = true;
        else if (a == "--sharp") cfg.smooth = cfg.xbrz = false;
        else if (a == "--nosound") cfg.nosound = true;
        else if (a == "--volume") cfg.volume = std::clamp(std::atoi(next().c_str()), 0, 100);
        else if (a == "--singlepage") cfg.dualpage = false;
        else if (a == "--trace") cfg.trace = true;
        else if (a == "--shots") cfg.shot_dir = next();
        else if (a == "--shot-interval") cfg.shot_interval = std::atof(next().c_str());
        else if (a == "--shot-presented") cfg.shot_presented = true;
        else if (a == "--quit-after") cfg.quit_after = std::atof(next().c_str());
        else if (a == "--script") cfg.script = next();
        else if (a == "--wav") cfg.wav = next();
        else if (a == "--") { while (++i < argc) cfg.args.push_back(argv[i]); }
        else { usage(); return a == "--help" || a == "-h" ? 0 : 2; }
    }

    if (!launcher) {
        if (game.empty()) game = ".";
        std::string err = play(cfg, game, setup);
        if (!err.empty()) std::fprintf(stderr, "%s\n", err.c_str());
        return err.empty() ? 0 : 1;
    }

    // settings window; after the game it opens again
    std::string message;
    for (;;) {
        const blub::LauncherResult r = blub::run_launcher(settings, ini, message);
        if (r == blub::LauncherResult::Quit) return 0;
        blub::HostConfig c = host_config(settings);
        c.trace = cfg.trace;                 // test options of the command line
        c.shot_dir = cfg.shot_dir;
        c.shot_interval = cfg.shot_interval;
        c.quit_after = cfg.quit_after;
        c.script = cfg.script;
        c.wav = cfg.wav;
        message = play(c, settings.game_dir, r == blub::LauncherResult::Setup);
        std::fflush(stdout);
    }
}
